version: '3'

services:
  php:
    build:
      context: .
    volumes:
        - ./:/var/www/blog:delegated

  web:
    image: nginx:1.17
    working_dir: /var/www/blog
    volumes:
      - ./:/var/www/blog:delegated
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
    ports:
      - "1919:80"
