version: '3'

services:
    php:
        build:
            context: .
        volumes:
            - ./:/var/www/blog:delegated

    web:
        image: nginx:1.17
        working_dir: /var/www/blog
        volumes:
            - ./:/var/www/blog:delegated
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:delegated
        ports:
            - "1919:80"
    db:
        image: mysql:8
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
        volumes:
            - ~/data/db/mysql/blog8:/var/lib/mysql:delegated
        ports:
            - "3304:3306"